### PR TITLE
赫蹏（hètí）TW5插件封装

### PR DESCRIPTION
**Pull request by Zacharia2**
heti项目：https://github.com/sivan/heti

演示网址：https://sivan.github.io/heti/#example-verse

### CODE REVIEW

**Comment by Zacharia2** [comment]
为太微封装成插件

**Comment by linonetwo** [comment]
里面填的 [https://github.com/Zacharia2/tw5-heti-plugi](https://github.com/Zacharia2/tw5-heti-plugi) 咋打不开了

**Comment by Zacharia2** [comment]
都可以打开呀

**Comment by Zacharia2** [comment]
"cpl.source": "https://github.com/Zacharia2/tw5-heti-plugin",
        "cpl.documentation": "https://zacharia2.github.io/tw5-heti-plugin/",

**Pull request merged**
